# Generated by Django 5.1.2 on 2025-03-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transactionhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('total_amount', models.FloatField()),
            ],
        ),
    ]
